import { WebClient, type Block, type KnownBlock } from '@slack/web-api'

export function getSlackClient(botToken: string) {
  return new WebClient(botToken)
}

export function buildAuthUrl(state: string): string {
  const scopes = 'chat:write,channels:read,chat:write.public'
  const params = new URLSearchParams({
    client_id: process.env.SLACK_CLIENT_ID!,
    redirect_uri: `${process.env.NEXT_PUBLIC_APP_URL}/api/integrations/slack/callback`,
    scope: scopes,
    state,
  })
  return `https://slack.com/oauth/v2/authorize?${params}`
}

export interface SlackTokenResponse {
  ok: boolean
  access_token: string
  token_type: string
  bot_user_id: string
  team: { id: string; name: string }
  authed_user: { id: string }
  error?: string
}

export async function exchangeCode(code: string): Promise<SlackTokenResponse> {
  const res = await fetch('https://slack.com/api/oauth.v2.access', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      code,
      client_id: process.env.SLACK_CLIENT_ID!,
      client_secret: process.env.SLACK_CLIENT_SECRET!,
      redirect_uri: `${process.env.NEXT_PUBLIC_APP_URL}/api/integrations/slack/callback`,
    }),
  })
  return res.json()
}

export interface CompanyHealthData {
  health_score: number
  health_grade: string
  covered_roles: number
  total_roles: number
  drifted_count: number
  expiring_critical_count: number
  total_certified: number
}

export interface ExpiryRiskData {
  employee_name: string | null
  employee_email: string
  role_name: string
  days_until_expiry: number
  expiry_window: string
}

function gradeEmoji(grade: string): string {
  if (grade === 'healthy')         return '🟢'
  if (grade === 'needs_attention') return '🟡'
  return '🔴'
}

export async function sendDigest(
  botToken: string,
  channelId: string,
  health: CompanyHealthData,
  expiryItems: ExpiryRiskData[]
): Promise<void> {
  const client = getSlackClient(botToken)
  const blocks = buildDigestBlocks(health, expiryItems)

  await client.chat.postMessage({
    channel: channelId,
    text: `Weekly ops digest — Health score: ${health.health_score}/100`,
    blocks,
  })
}

function buildDigestBlocks(
  health: CompanyHealthData,
  expiryItems: ExpiryRiskData[]
): (Block | KnownBlock)[] {
  const emoji = gradeEmoji(health.health_grade)
  const scoreBar = buildScoreBar(health.health_score)

  const blocks: (Block | KnownBlock)[] = [
    {
      type: 'header',
      text: {
        type: 'plain_text',
        text: '📋 Weekly Ops Digest',
        emoji: true,
      },
    },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Health Score* ${emoji}\n${scoreBar} *${health.health_score}/100* — ${health.health_grade.replace('_', ' ')}`,
      },
    },
    {
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*Certified*\n${health.total_certified} employees` },
        { type: 'mrkdwn', text: `*Role Coverage*\n${health.covered_roles}/${health.total_roles} roles staffed` },
        { type: 'mrkdwn', text: `*Drifted Certs*\n${health.drifted_count} need review` },
        { type: 'mrkdwn', text: `*Expiring (7d)*\n${health.expiring_critical_count} critical` },
      ],
    },
    { type: 'divider' },
  ]

  if (expiryItems.length > 0) {
    const top5 = expiryItems.slice(0, 5)
    const lines = top5.map((e) => {
      const name = e.employee_name ?? e.employee_email
      const urgency = e.days_until_expiry <= 3 ? '🔴' : e.days_until_expiry <= 7 ? '🟡' : '🟠'
      return `${urgency} *${name}* — ${e.role_name} (${e.days_until_expiry}d left)`
    })

    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*⚠️ Expiring Soon*\n${lines.join('\n')}`,
      },
    })
  } else {
    blocks.push({
      type: 'section',
      text: { type: 'mrkdwn', text: '✅ *No certifications expiring this week*' },
    })
  }

  blocks.push({
    type: 'context',
    elements: [
      {
        type: 'mrkdwn',
        text: `Generated by CompanyApp · ${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}`,
      },
    ],
  })

  return blocks
}

function buildScoreBar(score: number): string {
  const filled = Math.round(score / 10)
  return '█'.repeat(filled) + '░'.repeat(10 - filled)
}
